name: single-repo-multi-branch

on:
  push:
    branches:
      - main  # Trigger on the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository (main branch)
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          # ref: main  # Check out the main branch
          token: ${{ secrets.USER_TOKEN }}
          fetch-depth: 5

      # Set up Git
      - name: Set up Git
        run: |
          git config --global user.email "Workflow@githubactions.com"
          git config --global user.name "Github actions"

      # Fetch the L10NStaging branch
      - name: Fetch L10NStaging branch
        run: |
          git fetch origin L10NStaging:L10NStaging

      # Check for differences between main and L10NStaging
      - name: Check for changes between main and L10NStaging
        id: check_changes
        run: |
          if git diff --quiet main L10NStaging; then
            echo "No changes between main and L10NStaging."
            echo "::set-output name=has_changes::false"
          else
            echo "Changes detected between main and L10NStaging."
            echo "::set-output name=has_changes::true"
          fi
          
      # Check for L10NStagingRepoSpecific branch
      - name: Check if L10NStagingRepoSpecific branch exists
        id: check_branch
        run: |
          # cd main
          if git ls-remote --exit-code --heads origin L10NStagingRepoSpecific; then
            echo "Branch exists"
            echo "::set-output name=branch_exists::true"
          else
            echo "Branch does not exist"
            echo "::set-output name=branch_exists::false"
          fi

      # Check for existing PR from L10NStagingRepoSpecific to L10NStaging
      - name: Check if PR exists from L10NStagingRepoSpecific to L10NStaging
        id: check_pr_exists
        run: |
          # Use gh CLI to check for an existing open PR
          PR_EXISTS=$(gh pr list --base L10NStaging --head L10NStagingRepoSpecific --state open --json number --jq '.[0].number')
          if [ -z "$PR_EXISTS" ]; then
            echo "No existing PR found."
            echo "::set-output name=pr_exists::false"
          else
            echo "PR already exists: Matching #$PR_EXISTS"
            echo "::set-output name=pr_exists::true"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}

      - name: Create branch and Create PR
        if: steps.check_changes.outputs.has_changes == 'true' && steps.check_branch.outputs.branch_exists == 'false' &&  steps.check_pr_exists.outputs.pr_exists == 'false'
        run: |
          git checkout -b L10NStagingRepoSpecific main
          git push origin L10NStagingRepoSpecific
          gh pr create --title "Sync L10NStagingRepoSpecific" --body "Changes detected in main branch and synced with L10NStaging." --base L10NStaging --head L10NStagingRepoSpecific
        env:
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}

      # Update the branch if it exists and changes are found and branch found
      - name: Update branch and Update PR
        if: steps.check_changes.outputs.has_changes == 'true' && steps.check_branch.outputs.branch_exists == 'true' && steps.check_pr_exists.outputs.pr_exists == 'true'
        run: |
          git checkout -b L10NStagingRepoSpecific origin/L10NStagingRepoSpecific
          git pull origin main
          git push origin L10NStagingRepoSpecific
        env:
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}

      # Update the branch if it exists and changes are found and branch found
      - name: Update branch and Create PR
        if: steps.check_changes.outputs.has_changes == 'true' && steps.check_branch.outputs.branch_exists == 'true' && steps.check_pr_exists.outputs.pr_exists == 'false'
        run: |
          git checkout -b L10NStagingRepoSpecific origin/L10NStagingRepoSpecific
          git pull origin main
          git push origin L10NStagingRepoSpecific
          gh pr create --title "Sync L10NStagingRepoSpecific" --body "Changes detected in main branch and synced with L10NStaging." --base L10NStaging --head L10NStagingRepoSpecific
        env:
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}

      # # Optional: Clean up branches
      # - name: Clean up
      #   run: |
      #     git branch -d L10NStaging
      #     git branch -d L10NStagingRepoSpecific
